channels:
- conda-forge
dependencies:
- python=3.12.3
- pip<=24.0
- pip:
  - mlflow==2.19.0
  - cloudpickle==3.1.2
  - numpy==2.4.0
  - pandas==2.3.3
  - pyarrow==18.1.0
  - scikit-learn==1.8.0
  - scipy==1.16.3
name: mlflow-env
